const types={
  UPLOAD_STARTED:'UPLOAD_STARTED',
  UPLOAD_FILE:'UPLOAD_FILE',
  UPLOAD_FILE_ERROR:'UPLOAD_FILE_ERROR',
  DELETE_FILE:'DELETE_FILE',
  DELETE_FILE_ERROR:'DELETE_FILE_ERROR'
}

export default types;