const types={
  LOGIN_SUCCESS:'LOGIN_SUCCESS',
  LOGIN_ERROR:'LOGIN_ERROR',
  REGISTER_SUCCESS:'REGISTER_SUCCESS',
  REGISTER_ERROR:'REGISTER_ERROR',
  UPDATE_SUCCESS:"UPDATE_SUCCESS",
  UPDATE_ERROR:"UPDATE_ERROR",
  LOGOUT_SUCCESS:'LOGOUT_SUCCESS',
  ACCOUNT_ERROR_RESET:"ACCOUNT_ERROR_RESET",
}

export default types;