const types={
  CREATE_PRODUCT:'CREATE_PRODUCT',
  CREATE_PRODUCT_ERROR:'CREATE_PRODUCT_ERROR',
  UPDATE_PRODUCT:'UPDATE_PRODUCT',
  UPDATE_PRODUCT_ERROR:'UPDATE_PRODUCT_ERROR',
  REMOVE_PRODUCT:'REMOVE_PRODUCT',
  REMOVE_PRODUCT_ERROR:'REMOVE_PRODUCT_ERROR',
  UPDATE_PRODUCT_IMAGE:'UPDATE_PRODUCT_IMAGE',
  UPDATE_PRODUCT_IMAGE_ERROR:'UPDATE_PRODUCT_IMAGE_ERROR',
}

export default types;