const types={ 
  FULFIL_ORDER:"FULFIL_ORDER",
  FULFIL_ORDER_ERROR:"FULFIL_ORDER_ERROR",
  PAY_ORDER:"PAY_ORDER",
  VERIFIED_ORDER:"VERIFIED_ORDER",
  VERIFIED_ORDER_ERROR:"VERIFIED_ORDER_ERROR",
  PAY_ORDER_ERROR:"PAY_ORDER_ERROR",
  COMPLETE_ORDER:"COMPLETE_ORDER",
  COMPLETE_ORDER_ERROR:"COMPLETE_ORDER_ERROR", 
}

export default types;